# Configuration Netlify pour optimisations SEO et performance

[build]
  publish = "."
  command = ""

# Headers pour améliorer le SEO et la sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # Cache control pour les fichiers statiques
    Cache-Control = "public, max-age=31536000, immutable"

# Headers spécifiques pour HTML (pas de cache pour index.html)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers pour les images
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les CSS et JS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirections 301 pour SEO (exemples)
# [[redirects]]
#   from = "/old-page"
#   to = "/new-page"
#   status = 301

# Redirection des erreurs 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

